
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


CREATE TABLE `ESPtable2` (
  `id` int(5) NOT NULL,
  `PASSWORD` int(5) NOT NULL,
  `SENT_NUMBER_1` int(5) NOT NULL,
  `SENT_NUMBER_2` int(5) NOT NULL,
  `SENT_NUMBER_3` int(5) NOT NULL,

  `SENT_BOOL_1` tinyint(1) NOT NULL,

  `RECEIVED_BOOL1` int(1) NOT NULL,
  `RECEIVED_BOOL2` int(1) NOT NULL,
  `RECEIVED_BOOL3` int(1) NOT NULL,
  `RECEIVED_BOOL4` int(1) NOT NULL,
  `RECEIVED_BOOL5` int(1) NOT NULL,
  `RECEIVED_BOOL6` int(1) NOT NULL,

  `RECEIVED_BOOL_USA` int(1) NOT NULL,
  `RECEIVED_BOOL_GARAJ` int(1) NOT NULL,
  `RECEIVED_BOOL_GEAM1` int(1) NOT NULL,
  `RECEIVED_BOOL_GEAM2` int(1) NOT NULL,

  `RECEIVED_BOOL_SMOKE` int(1) NOT NULL,

  `RECEIVED_NUM1` int(5) NOT NULL,
  `RECEIVED_NUM2` int(5) NOT NULL,
  `RECEIVED_NUM3` int(5) NOT NULL,

  `TEXT_1` text CHARACTER SET latin1 COLLATE latin1_spanish_ci NOT NULL,
  `NAME` text CHARACTER SET latin1 COLLATE latin1_spanish_ci NOT NULL,
  `PASS` text CHARACTER SET latin1 COLLATE latin1_spanish_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


INSERT INTO `ESPtable2` (`id`, `PASSWORD`, `SENT_NUMBER_1`, `SENT_NUMBER_2`,`SENT_NUMBER_3`,`SENT_BOOL_1`, `RECEIVED_BOOL1`, `RECEIVED_BOOL2`, `RECEIVED_BOOL3`, `RECEIVED_BOOL4`, `RECEIVED_BOOL5`,`RECEIVED_BOOL6`,`RECEIVED_BOOL_USA`,`RECEIVED_BOOL_GARAJ`,`RECEIVED_BOOL_GEAM1`,`RECEIVED_BOOL_GEAM2`,`RECEIVED_BOOL_SMOKE`, `RECEIVED_NUM1`, `RECEIVED_NUM2`,`RECEIVED_NUM3`, `TEXT_1`,`NAME`, `PASS`) VALUES
(99999, 12345, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,'nimic','gligor','gligglig');

ALTER TABLE `ESPtable2`
  ADD PRIMARY KEY (`id`);

ALTER TABLE `ESPtable2`
  MODIFY `id` int(5) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=100000;
